[admin]
basename=nd_monophyly
glottolog_release=5.0
[MCMC]
chainlength=20000000
[languages]
monophyly=True
monophyly_levels=1
[model nd_monophyly]
model=bsvs
data=cognates_full_gl.csv
rate_variation=False
[clock default]
type=strict
